// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: download_buffer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// リクエスト
type BufferDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []string               `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferDownloadRequest) Reset() {
	*x = BufferDownloadRequest{}
	mi := &file_download_buffer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferDownloadRequest) ProtoMessage() {}

func (x *BufferDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_download_buffer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferDownloadRequest.ProtoReflect.Descriptor instead.
func (*BufferDownloadRequest) Descriptor() ([]byte, []int) {
	return file_download_buffer_proto_rawDescGZIP(), []int{0}
}

func (x *BufferDownloadRequest) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *BufferDownloadRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *BufferDownloadRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

// バッファレスポンス（CSVをそのままバイナリで）
type BufferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvData       []byte                 `protobuf:"bytes,1,opt,name=csv_data,json=csvData,proto3" json:"csv_data,omitempty"` // CSVファイルの内容をそのまま
	RecordCount   int32                  `protobuf:"varint,2,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "text/csv"
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferResponse) Reset() {
	*x = BufferResponse{}
	mi := &file_download_buffer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferResponse) ProtoMessage() {}

func (x *BufferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_buffer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferResponse.ProtoReflect.Descriptor instead.
func (*BufferResponse) Descriptor() ([]byte, []int) {
	return file_download_buffer_proto_rawDescGZIP(), []int{1}
}

func (x *BufferResponse) GetCsvData() []byte {
	if x != nil {
		return x.CsvData
	}
	return nil
}

func (x *BufferResponse) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *BufferResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BufferResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// ストリーミング用チャンク
type ChunkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Chunk          []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"` // データの一部（例: 1MB chunks）
	IsLast         bool                   `protobuf:"varint,2,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChunkResponse) Reset() {
	*x = ChunkResponse{}
	mi := &file_download_buffer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkResponse) ProtoMessage() {}

func (x *ChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_buffer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkResponse.ProtoReflect.Descriptor instead.
func (*ChunkResponse) Descriptor() ([]byte, []int) {
	return file_download_buffer_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ChunkResponse) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *ChunkResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// Protocol Buffersネイティブ形式
type ProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ETCRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Metadata      *RecordMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoResponse) Reset() {
	*x = ProtoResponse{}
	mi := &file_download_buffer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoResponse) ProtoMessage() {}

func (x *ProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_buffer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoResponse.ProtoReflect.Descriptor instead.
func (*ProtoResponse) Descriptor() ([]byte, []int) {
	return file_download_buffer_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoResponse) GetRecords() []*ETCRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ProtoResponse) GetMetadata() *RecordMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ETCRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	EntranceIc    string                 `protobuf:"bytes,3,opt,name=entrance_ic,json=entranceIc,proto3" json:"entrance_ic,omitempty"`
	ExitIc        string                 `protobuf:"bytes,4,opt,name=exit_ic,json=exitIc,proto3" json:"exit_ic,omitempty"`
	Fare          int32                  `protobuf:"varint,5,opt,name=fare,proto3" json:"fare,omitempty"`
	VehicleNumber string                 `protobuf:"bytes,6,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	CardNumber    string                 `protobuf:"bytes,7,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ETCRecord) Reset() {
	*x = ETCRecord{}
	mi := &file_download_buffer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETCRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETCRecord) ProtoMessage() {}

func (x *ETCRecord) ProtoReflect() protoreflect.Message {
	mi := &file_download_buffer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETCRecord.ProtoReflect.Descriptor instead.
func (*ETCRecord) Descriptor() ([]byte, []int) {
	return file_download_buffer_proto_rawDescGZIP(), []int{4}
}

func (x *ETCRecord) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ETCRecord) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ETCRecord) GetEntranceIc() string {
	if x != nil {
		return x.EntranceIc
	}
	return ""
}

func (x *ETCRecord) GetExitIc() string {
	if x != nil {
		return x.ExitIc
	}
	return ""
}

func (x *ETCRecord) GetFare() int32 {
	if x != nil {
		return x.Fare
	}
	return 0
}

func (x *ETCRecord) GetVehicleNumber() string {
	if x != nil {
		return x.VehicleNumber
	}
	return ""
}

func (x *ETCRecord) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

type RecordMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	DownloadedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=downloaded_at,json=downloadedAt,proto3" json:"downloaded_at,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordMetadata) Reset() {
	*x = RecordMetadata{}
	mi := &file_download_buffer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMetadata) ProtoMessage() {}

func (x *RecordMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_download_buffer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMetadata.ProtoReflect.Descriptor instead.
func (*RecordMetadata) Descriptor() ([]byte, []int) {
	return file_download_buffer_proto_rawDescGZIP(), []int{5}
}

func (x *RecordMetadata) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *RecordMetadata) GetDownloadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DownloadedAt
	}
	return nil
}

func (x *RecordMetadata) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

var File_download_buffer_proto protoreflect.FileDescriptor

const file_download_buffer_proto_rawDesc = "" +
	"\n" +
	"\x15download_buffer.proto\x12\x16etc_meisai.download.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n" +
	"\x15BufferDownloadRequest\x12\x1a\n" +
	"\baccounts\x18\x01 \x03(\tR\baccounts\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\"\x90\x01\n" +
	"\x0eBufferResponse\x12\x19\n" +
	"\bcsv_data\x18\x01 \x01(\fR\acsvData\x12!\n" +
	"\frecord_count\x18\x02 \x01(\x05R\vrecordCount\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"g\n" +
	"\rChunkResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x17\n" +
	"\ais_last\x18\x02 \x01(\bR\x06isLast\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x05R\x0esequenceNumber\"\x90\x01\n" +
	"\rProtoResponse\x12;\n" +
	"\arecords\x18\x01 \x03(\v2!.etc_meisai.download.v2.ETCRecordR\arecords\x12B\n" +
	"\bmetadata\x18\x02 \x01(\v2&.etc_meisai.download.v2.RecordMetadataR\bmetadata\"\xc9\x01\n" +
	"\tETCRecord\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x12\x1f\n" +
	"\ventrance_ic\x18\x03 \x01(\tR\n" +
	"entranceIc\x12\x17\n" +
	"\aexit_ic\x18\x04 \x01(\tR\x06exitIc\x12\x12\n" +
	"\x04fare\x18\x05 \x01(\x05R\x04fare\x12%\n" +
	"\x0evehicle_number\x18\x06 \x01(\tR\rvehicleNumber\x12\x1f\n" +
	"\vcard_number\x18\a \x01(\tR\n" +
	"cardNumber\"\x91\x01\n" +
	"\x0eRecordMetadata\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12?\n" +
	"\rdownloaded_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fdownloadedAt\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId2\xd5\x02\n" +
	"\x15DownloadBufferService\x12i\n" +
	"\x10DownloadAsBuffer\x12-.etc_meisai.download.v2.BufferDownloadRequest\x1a&.etc_meisai.download.v2.BufferResponse\x12h\n" +
	"\x0eDownloadStream\x12-.etc_meisai.download.v2.BufferDownloadRequest\x1a%.etc_meisai.download.v2.ChunkResponse0\x01\x12g\n" +
	"\x0fDownloadAsProto\x12-.etc_meisai.download.v2.BufferDownloadRequest\x1a%.etc_meisai.download.v2.ProtoResponseB4Z2github.com/yhonda-ohishi/etc_meisai_scraper/src/pbb\x06proto3"

var (
	file_download_buffer_proto_rawDescOnce sync.Once
	file_download_buffer_proto_rawDescData []byte
)

func file_download_buffer_proto_rawDescGZIP() []byte {
	file_download_buffer_proto_rawDescOnce.Do(func() {
		file_download_buffer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_download_buffer_proto_rawDesc), len(file_download_buffer_proto_rawDesc)))
	})
	return file_download_buffer_proto_rawDescData
}

var file_download_buffer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_download_buffer_proto_goTypes = []any{
	(*BufferDownloadRequest)(nil), // 0: etc_meisai.download.v2.BufferDownloadRequest
	(*BufferResponse)(nil),        // 1: etc_meisai.download.v2.BufferResponse
	(*ChunkResponse)(nil),         // 2: etc_meisai.download.v2.ChunkResponse
	(*ProtoResponse)(nil),         // 3: etc_meisai.download.v2.ProtoResponse
	(*ETCRecord)(nil),             // 4: etc_meisai.download.v2.ETCRecord
	(*RecordMetadata)(nil),        // 5: etc_meisai.download.v2.RecordMetadata
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_download_buffer_proto_depIdxs = []int32{
	4, // 0: etc_meisai.download.v2.ProtoResponse.records:type_name -> etc_meisai.download.v2.ETCRecord
	5, // 1: etc_meisai.download.v2.ProtoResponse.metadata:type_name -> etc_meisai.download.v2.RecordMetadata
	6, // 2: etc_meisai.download.v2.RecordMetadata.downloaded_at:type_name -> google.protobuf.Timestamp
	0, // 3: etc_meisai.download.v2.DownloadBufferService.DownloadAsBuffer:input_type -> etc_meisai.download.v2.BufferDownloadRequest
	0, // 4: etc_meisai.download.v2.DownloadBufferService.DownloadStream:input_type -> etc_meisai.download.v2.BufferDownloadRequest
	0, // 5: etc_meisai.download.v2.DownloadBufferService.DownloadAsProto:input_type -> etc_meisai.download.v2.BufferDownloadRequest
	1, // 6: etc_meisai.download.v2.DownloadBufferService.DownloadAsBuffer:output_type -> etc_meisai.download.v2.BufferResponse
	2, // 7: etc_meisai.download.v2.DownloadBufferService.DownloadStream:output_type -> etc_meisai.download.v2.ChunkResponse
	3, // 8: etc_meisai.download.v2.DownloadBufferService.DownloadAsProto:output_type -> etc_meisai.download.v2.ProtoResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_download_buffer_proto_init() }
func file_download_buffer_proto_init() {
	if File_download_buffer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_download_buffer_proto_rawDesc), len(file_download_buffer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_download_buffer_proto_goTypes,
		DependencyIndexes: file_download_buffer_proto_depIdxs,
		MessageInfos:      file_download_buffer_proto_msgTypes,
	}.Build()
	File_download_buffer_proto = out.File
	file_download_buffer_proto_goTypes = nil
	file_download_buffer_proto_depIdxs = nil
}
