// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: download.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ダウンロードリクエスト
type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []string               `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_download_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadRequest) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *DownloadRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *DownloadRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *DownloadRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// ダウンロードレスポンス
type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecordCount   int32                  `protobuf:"varint,2,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	CsvPath       string                 `protobuf:"bytes,3,opt,name=csv_path,json=csvPath,proto3" json:"csv_path,omitempty"`
	Records       []*ETCMeisaiRecord     `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_download_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DownloadResponse) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *DownloadResponse) GetCsvPath() string {
	if x != nil {
		return x.CsvPath
	}
	return ""
}

func (x *DownloadResponse) GetRecords() []*ETCMeisaiRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *DownloadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ダウンロードジョブレスポンス
type DownloadJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadJobResponse) Reset() {
	*x = DownloadJobResponse{}
	mi := &file_download_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadJobResponse) ProtoMessage() {}

func (x *DownloadJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadJobResponse.ProtoReflect.Descriptor instead.
func (*DownloadJobResponse) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DownloadJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DownloadJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ジョブステータス取得リクエスト
type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_download_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// ジョブステータス
type JobStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	TotalRecords  int32                  `protobuf:"varint,4,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_download_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{4}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatus) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *JobStatus) GetTotalRecords() int32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *JobStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *JobStatus) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// アカウントID取得リクエスト
type GetAllAccountIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAccountIDsRequest) Reset() {
	*x = GetAllAccountIDsRequest{}
	mi := &file_download_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAccountIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAccountIDsRequest) ProtoMessage() {}

func (x *GetAllAccountIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAccountIDsRequest.ProtoReflect.Descriptor instead.
func (*GetAllAccountIDsRequest) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{5}
}

// アカウントID取得レスポンス
type GetAllAccountIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIds    []string               `protobuf:"bytes,1,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAccountIDsResponse) Reset() {
	*x = GetAllAccountIDsResponse{}
	mi := &file_download_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAccountIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAccountIDsResponse) ProtoMessage() {}

func (x *GetAllAccountIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAccountIDsResponse.ProtoReflect.Descriptor instead.
func (*GetAllAccountIDsResponse) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllAccountIDsResponse) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

// ETC明細レコード
type ETCMeisaiRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UsageDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=usage_date,json=usageDate,proto3" json:"usage_date,omitempty"`
	EntryIc       string                 `protobuf:"bytes,4,opt,name=entry_ic,json=entryIc,proto3" json:"entry_ic,omitempty"`
	ExitIc        string                 `protobuf:"bytes,5,opt,name=exit_ic,json=exitIc,proto3" json:"exit_ic,omitempty"`
	VehicleNumber string                 `protobuf:"bytes,6,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	EtcCardNumber string                 `protobuf:"bytes,7,opt,name=etc_card_number,json=etcCardNumber,proto3" json:"etc_card_number,omitempty"`
	Amount        int32                  `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	CsvFileName   string                 `protobuf:"bytes,9,opt,name=csv_file_name,json=csvFileName,proto3" json:"csv_file_name,omitempty"`
	DownloadedAt  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=downloaded_at,json=downloadedAt,proto3" json:"downloaded_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ETCMeisaiRecord) Reset() {
	*x = ETCMeisaiRecord{}
	mi := &file_download_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETCMeisaiRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETCMeisaiRecord) ProtoMessage() {}

func (x *ETCMeisaiRecord) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETCMeisaiRecord.ProtoReflect.Descriptor instead.
func (*ETCMeisaiRecord) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{7}
}

func (x *ETCMeisaiRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ETCMeisaiRecord) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ETCMeisaiRecord) GetUsageDate() *timestamppb.Timestamp {
	if x != nil {
		return x.UsageDate
	}
	return nil
}

func (x *ETCMeisaiRecord) GetEntryIc() string {
	if x != nil {
		return x.EntryIc
	}
	return ""
}

func (x *ETCMeisaiRecord) GetExitIc() string {
	if x != nil {
		return x.ExitIc
	}
	return ""
}

func (x *ETCMeisaiRecord) GetVehicleNumber() string {
	if x != nil {
		return x.VehicleNumber
	}
	return ""
}

func (x *ETCMeisaiRecord) GetEtcCardNumber() string {
	if x != nil {
		return x.EtcCardNumber
	}
	return ""
}

func (x *ETCMeisaiRecord) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ETCMeisaiRecord) GetCsvFileName() string {
	if x != nil {
		return x.CsvFileName
	}
	return ""
}

func (x *ETCMeisaiRecord) GetDownloadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DownloadedAt
	}
	return nil
}

func (x *ETCMeisaiRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ETCMeisaiRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_download_proto protoreflect.FileDescriptor

const file_download_proto_rawDesc = "" +
	"\n" +
	"\x0edownload.proto\x12\x16etc_meisai.download.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\x0fDownloadRequest\x12\x1a\n" +
	"\baccounts\x18\x01 \x03(\tR\baccounts\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\xc3\x01\n" +
	"\x10DownloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\frecord_count\x18\x02 \x01(\x05R\vrecordCount\x12\x19\n" +
	"\bcsv_path\x18\x03 \x01(\tR\acsvPath\x12A\n" +
	"\arecords\x18\x04 \x03(\v2'.etc_meisai.download.v1.ETCMeisaiRecordR\arecords\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"^\n" +
	"\x13DownloadJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x9a\x02\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12#\n" +
	"\rtotal_records\x18\x04 \x01(\x05R\ftotalRecords\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x19\n" +
	"\x17GetAllAccountIDsRequest\";\n" +
	"\x18GetAllAccountIDsResponse\x12\x1f\n" +
	"\vaccount_ids\x18\x01 \x03(\tR\n" +
	"accountIds\"\xf1\x03\n" +
	"\x0fETCMeisaiRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x129\n" +
	"\n" +
	"usage_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tusageDate\x12\x19\n" +
	"\bentry_ic\x18\x04 \x01(\tR\aentryIc\x12\x17\n" +
	"\aexit_ic\x18\x05 \x01(\tR\x06exitIc\x12%\n" +
	"\x0evehicle_number\x18\x06 \x01(\tR\rvehicleNumber\x12&\n" +
	"\x0fetc_card_number\x18\a \x01(\tR\retcCardNumber\x12\x16\n" +
	"\x06amount\x18\b \x01(\x05R\x06amount\x12\"\n" +
	"\rcsv_file_name\x18\t \x01(\tR\vcsvFileName\x12?\n" +
	"\rdownloaded_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\fdownloadedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xb2\x03\n" +
	"\x0fDownloadService\x12a\n" +
	"\fDownloadSync\x12'.etc_meisai.download.v1.DownloadRequest\x1a(.etc_meisai.download.v1.DownloadResponse\x12e\n" +
	"\rDownloadAsync\x12'.etc_meisai.download.v1.DownloadRequest\x1a+.etc_meisai.download.v1.DownloadJobResponse\x12^\n" +
	"\fGetJobStatus\x12+.etc_meisai.download.v1.GetJobStatusRequest\x1a!.etc_meisai.download.v1.JobStatus\x12u\n" +
	"\x10GetAllAccountIDs\x12/.etc_meisai.download.v1.GetAllAccountIDsRequest\x1a0.etc_meisai.download.v1.GetAllAccountIDsResponseB4Z2github.com/yhonda-ohishi/etc_meisai_scraper/src/pbb\x06proto3"

var (
	file_download_proto_rawDescOnce sync.Once
	file_download_proto_rawDescData []byte
)

func file_download_proto_rawDescGZIP() []byte {
	file_download_proto_rawDescOnce.Do(func() {
		file_download_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_download_proto_rawDesc), len(file_download_proto_rawDesc)))
	})
	return file_download_proto_rawDescData
}

var file_download_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_download_proto_goTypes = []any{
	(*DownloadRequest)(nil),          // 0: etc_meisai.download.v1.DownloadRequest
	(*DownloadResponse)(nil),         // 1: etc_meisai.download.v1.DownloadResponse
	(*DownloadJobResponse)(nil),      // 2: etc_meisai.download.v1.DownloadJobResponse
	(*GetJobStatusRequest)(nil),      // 3: etc_meisai.download.v1.GetJobStatusRequest
	(*JobStatus)(nil),                // 4: etc_meisai.download.v1.JobStatus
	(*GetAllAccountIDsRequest)(nil),  // 5: etc_meisai.download.v1.GetAllAccountIDsRequest
	(*GetAllAccountIDsResponse)(nil), // 6: etc_meisai.download.v1.GetAllAccountIDsResponse
	(*ETCMeisaiRecord)(nil),          // 7: etc_meisai.download.v1.ETCMeisaiRecord
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_download_proto_depIdxs = []int32{
	7,  // 0: etc_meisai.download.v1.DownloadResponse.records:type_name -> etc_meisai.download.v1.ETCMeisaiRecord
	8,  // 1: etc_meisai.download.v1.JobStatus.started_at:type_name -> google.protobuf.Timestamp
	8,  // 2: etc_meisai.download.v1.JobStatus.completed_at:type_name -> google.protobuf.Timestamp
	8,  // 3: etc_meisai.download.v1.ETCMeisaiRecord.usage_date:type_name -> google.protobuf.Timestamp
	8,  // 4: etc_meisai.download.v1.ETCMeisaiRecord.downloaded_at:type_name -> google.protobuf.Timestamp
	8,  // 5: etc_meisai.download.v1.ETCMeisaiRecord.created_at:type_name -> google.protobuf.Timestamp
	8,  // 6: etc_meisai.download.v1.ETCMeisaiRecord.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: etc_meisai.download.v1.DownloadService.DownloadSync:input_type -> etc_meisai.download.v1.DownloadRequest
	0,  // 8: etc_meisai.download.v1.DownloadService.DownloadAsync:input_type -> etc_meisai.download.v1.DownloadRequest
	3,  // 9: etc_meisai.download.v1.DownloadService.GetJobStatus:input_type -> etc_meisai.download.v1.GetJobStatusRequest
	5,  // 10: etc_meisai.download.v1.DownloadService.GetAllAccountIDs:input_type -> etc_meisai.download.v1.GetAllAccountIDsRequest
	1,  // 11: etc_meisai.download.v1.DownloadService.DownloadSync:output_type -> etc_meisai.download.v1.DownloadResponse
	2,  // 12: etc_meisai.download.v1.DownloadService.DownloadAsync:output_type -> etc_meisai.download.v1.DownloadJobResponse
	4,  // 13: etc_meisai.download.v1.DownloadService.GetJobStatus:output_type -> etc_meisai.download.v1.JobStatus
	6,  // 14: etc_meisai.download.v1.DownloadService.GetAllAccountIDs:output_type -> etc_meisai.download.v1.GetAllAccountIDsResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_download_proto_init() }
func file_download_proto_init() {
	if File_download_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_download_proto_rawDesc), len(file_download_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_download_proto_goTypes,
		DependencyIndexes: file_download_proto_depIdxs,
		MessageInfos:      file_download_proto_msgTypes,
	}.Build()
	File_download_proto = out.File
	file_download_proto_goTypes = nil
	file_download_proto_depIdxs = nil
}
