// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: etc_meisai.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// マッピングステータス
type MappingStatus int32

const (
	MappingStatus_MAPPING_STATUS_UNSPECIFIED MappingStatus = 0
	MappingStatus_MAPPING_STATUS_ACTIVE      MappingStatus = 1
	MappingStatus_MAPPING_STATUS_INACTIVE    MappingStatus = 2
	MappingStatus_MAPPING_STATUS_PENDING     MappingStatus = 3
	MappingStatus_MAPPING_STATUS_REJECTED    MappingStatus = 4
)

// Enum value maps for MappingStatus.
var (
	MappingStatus_name = map[int32]string{
		0: "MAPPING_STATUS_UNSPECIFIED",
		1: "MAPPING_STATUS_ACTIVE",
		2: "MAPPING_STATUS_INACTIVE",
		3: "MAPPING_STATUS_PENDING",
		4: "MAPPING_STATUS_REJECTED",
	}
	MappingStatus_value = map[string]int32{
		"MAPPING_STATUS_UNSPECIFIED": 0,
		"MAPPING_STATUS_ACTIVE":      1,
		"MAPPING_STATUS_INACTIVE":    2,
		"MAPPING_STATUS_PENDING":     3,
		"MAPPING_STATUS_REJECTED":    4,
	}
)

func (x MappingStatus) Enum() *MappingStatus {
	p := new(MappingStatus)
	*p = x
	return p
}

func (x MappingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MappingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_etc_meisai_proto_enumTypes[0].Descriptor()
}

func (MappingStatus) Type() protoreflect.EnumType {
	return &file_etc_meisai_proto_enumTypes[0]
}

func (x MappingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MappingStatus.Descriptor instead.
func (MappingStatus) EnumDescriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{0}
}

// インポートステータス
type ImportStatus int32

const (
	ImportStatus_IMPORT_STATUS_UNSPECIFIED ImportStatus = 0
	ImportStatus_IMPORT_STATUS_PENDING     ImportStatus = 1
	ImportStatus_IMPORT_STATUS_PROCESSING  ImportStatus = 2
	ImportStatus_IMPORT_STATUS_COMPLETED   ImportStatus = 3
	ImportStatus_IMPORT_STATUS_FAILED      ImportStatus = 4
	ImportStatus_IMPORT_STATUS_CANCELLED   ImportStatus = 5
)

// Enum value maps for ImportStatus.
var (
	ImportStatus_name = map[int32]string{
		0: "IMPORT_STATUS_UNSPECIFIED",
		1: "IMPORT_STATUS_PENDING",
		2: "IMPORT_STATUS_PROCESSING",
		3: "IMPORT_STATUS_COMPLETED",
		4: "IMPORT_STATUS_FAILED",
		5: "IMPORT_STATUS_CANCELLED",
	}
	ImportStatus_value = map[string]int32{
		"IMPORT_STATUS_UNSPECIFIED": 0,
		"IMPORT_STATUS_PENDING":     1,
		"IMPORT_STATUS_PROCESSING":  2,
		"IMPORT_STATUS_COMPLETED":   3,
		"IMPORT_STATUS_FAILED":      4,
		"IMPORT_STATUS_CANCELLED":   5,
	}
)

func (x ImportStatus) Enum() *ImportStatus {
	p := new(ImportStatus)
	*p = x
	return p
}

func (x ImportStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImportStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_etc_meisai_proto_enumTypes[1].Descriptor()
}

func (ImportStatus) Type() protoreflect.EnumType {
	return &file_etc_meisai_proto_enumTypes[1]
}

func (x ImportStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImportStatus.Descriptor instead.
func (ImportStatus) EnumDescriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{1}
}

type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASC         SortOrder = 1
	SortOrder_SORT_ORDER_DESC        SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_etc_meisai_proto_enumTypes[2].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_etc_meisai_proto_enumTypes[2]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{2}
}

// ETC明細レコード
type ETCMeisaiRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD format
	Time          string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"` // HH:MM:SS format
	EntranceIc    string                 `protobuf:"bytes,5,opt,name=entrance_ic,json=entranceIc,proto3" json:"entrance_ic,omitempty"`
	ExitIc        string                 `protobuf:"bytes,6,opt,name=exit_ic,json=exitIc,proto3" json:"exit_ic,omitempty"`
	TollAmount    int32                  `protobuf:"varint,7,opt,name=toll_amount,json=tollAmount,proto3" json:"toll_amount,omitempty"`
	CarNumber     string                 `protobuf:"bytes,8,opt,name=car_number,json=carNumber,proto3" json:"car_number,omitempty"`
	EtcCardNumber string                 `protobuf:"bytes,9,opt,name=etc_card_number,json=etcCardNumber,proto3" json:"etc_card_number,omitempty"`
	EtcNum        *string                `protobuf:"bytes,10,opt,name=etc_num,json=etcNum,proto3,oneof" json:"etc_num,omitempty"`
	DtakoRowId    *int64                 `protobuf:"varint,11,opt,name=dtako_row_id,json=dtakoRowId,proto3,oneof" json:"dtako_row_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ETCMeisaiRecord) Reset() {
	*x = ETCMeisaiRecord{}
	mi := &file_etc_meisai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETCMeisaiRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETCMeisaiRecord) ProtoMessage() {}

func (x *ETCMeisaiRecord) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETCMeisaiRecord.ProtoReflect.Descriptor instead.
func (*ETCMeisaiRecord) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{0}
}

func (x *ETCMeisaiRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ETCMeisaiRecord) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ETCMeisaiRecord) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ETCMeisaiRecord) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ETCMeisaiRecord) GetEntranceIc() string {
	if x != nil {
		return x.EntranceIc
	}
	return ""
}

func (x *ETCMeisaiRecord) GetExitIc() string {
	if x != nil {
		return x.ExitIc
	}
	return ""
}

func (x *ETCMeisaiRecord) GetTollAmount() int32 {
	if x != nil {
		return x.TollAmount
	}
	return 0
}

func (x *ETCMeisaiRecord) GetCarNumber() string {
	if x != nil {
		return x.CarNumber
	}
	return ""
}

func (x *ETCMeisaiRecord) GetEtcCardNumber() string {
	if x != nil {
		return x.EtcCardNumber
	}
	return ""
}

func (x *ETCMeisaiRecord) GetEtcNum() string {
	if x != nil && x.EtcNum != nil {
		return *x.EtcNum
	}
	return ""
}

func (x *ETCMeisaiRecord) GetDtakoRowId() int64 {
	if x != nil && x.DtakoRowId != nil {
		return *x.DtakoRowId
	}
	return 0
}

func (x *ETCMeisaiRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ETCMeisaiRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// マッピング情報
type ETCMapping struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EtcRecordId      int64                  `protobuf:"varint,2,opt,name=etc_record_id,json=etcRecordId,proto3" json:"etc_record_id,omitempty"`
	EtcRecord        *ETCMeisaiRecord       `protobuf:"bytes,3,opt,name=etc_record,json=etcRecord,proto3" json:"etc_record,omitempty"`
	MappingType      string                 `protobuf:"bytes,4,opt,name=mapping_type,json=mappingType,proto3" json:"mapping_type,omitempty"`
	MappedEntityId   int64                  `protobuf:"varint,5,opt,name=mapped_entity_id,json=mappedEntityId,proto3" json:"mapped_entity_id,omitempty"`
	MappedEntityType string                 `protobuf:"bytes,6,opt,name=mapped_entity_type,json=mappedEntityType,proto3" json:"mapped_entity_type,omitempty"`
	Confidence       float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Status           MappingStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=etc_meisai.v1.MappingStatus" json:"status,omitempty"`
	Metadata         *structpb.Struct       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ETCMapping) Reset() {
	*x = ETCMapping{}
	mi := &file_etc_meisai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETCMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETCMapping) ProtoMessage() {}

func (x *ETCMapping) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETCMapping.ProtoReflect.Descriptor instead.
func (*ETCMapping) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{1}
}

func (x *ETCMapping) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ETCMapping) GetEtcRecordId() int64 {
	if x != nil {
		return x.EtcRecordId
	}
	return 0
}

func (x *ETCMapping) GetEtcRecord() *ETCMeisaiRecord {
	if x != nil {
		return x.EtcRecord
	}
	return nil
}

func (x *ETCMapping) GetMappingType() string {
	if x != nil {
		return x.MappingType
	}
	return ""
}

func (x *ETCMapping) GetMappedEntityId() int64 {
	if x != nil {
		return x.MappedEntityId
	}
	return 0
}

func (x *ETCMapping) GetMappedEntityType() string {
	if x != nil {
		return x.MappedEntityType
	}
	return ""
}

func (x *ETCMapping) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ETCMapping) GetStatus() MappingStatus {
	if x != nil {
		return x.Status
	}
	return MappingStatus_MAPPING_STATUS_UNSPECIFIED
}

func (x *ETCMapping) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ETCMapping) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ETCMapping) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ETCMapping) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// インポートセッション
type ImportSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	AccountType   string                 `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Status        ImportStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=etc_meisai.v1.ImportStatus" json:"status,omitempty"`
	TotalRows     int32                  `protobuf:"varint,7,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	ProcessedRows int32                  `protobuf:"varint,8,opt,name=processed_rows,json=processedRows,proto3" json:"processed_rows,omitempty"`
	SuccessRows   int32                  `protobuf:"varint,9,opt,name=success_rows,json=successRows,proto3" json:"success_rows,omitempty"`
	ErrorRows     int32                  `protobuf:"varint,10,opt,name=error_rows,json=errorRows,proto3" json:"error_rows,omitempty"`
	DuplicateRows int32                  `protobuf:"varint,11,opt,name=duplicate_rows,json=duplicateRows,proto3" json:"duplicate_rows,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	ErrorLog      []*ImportError         `protobuf:"bytes,14,rep,name=error_log,json=errorLog,proto3" json:"error_log,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,15,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSession) Reset() {
	*x = ImportSession{}
	mi := &file_etc_meisai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSession) ProtoMessage() {}

func (x *ImportSession) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSession.ProtoReflect.Descriptor instead.
func (*ImportSession) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{2}
}

func (x *ImportSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImportSession) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *ImportSession) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ImportSession) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ImportSession) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ImportSession) GetStatus() ImportStatus {
	if x != nil {
		return x.Status
	}
	return ImportStatus_IMPORT_STATUS_UNSPECIFIED
}

func (x *ImportSession) GetTotalRows() int32 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *ImportSession) GetProcessedRows() int32 {
	if x != nil {
		return x.ProcessedRows
	}
	return 0
}

func (x *ImportSession) GetSuccessRows() int32 {
	if x != nil {
		return x.SuccessRows
	}
	return 0
}

func (x *ImportSession) GetErrorRows() int32 {
	if x != nil {
		return x.ErrorRows
	}
	return 0
}

func (x *ImportSession) GetDuplicateRows() int32 {
	if x != nil {
		return x.DuplicateRows
	}
	return 0
}

func (x *ImportSession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ImportSession) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ImportSession) GetErrorLog() []*ImportError {
	if x != nil {
		return x.ErrorLog
	}
	return nil
}

func (x *ImportSession) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ImportSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// インポートエラー
type ImportError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowNumber     int32                  `protobuf:"varint,1,opt,name=row_number,json=rowNumber,proto3" json:"row_number,omitempty"`
	ErrorType     string                 `protobuf:"bytes,2,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RawData       string                 `protobuf:"bytes,4,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportError) Reset() {
	*x = ImportError{}
	mi := &file_etc_meisai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportError) ProtoMessage() {}

func (x *ImportError) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportError.ProtoReflect.Descriptor instead.
func (*ImportError) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{3}
}

func (x *ImportError) GetRowNumber() int32 {
	if x != nil {
		return x.RowNumber
	}
	return 0
}

func (x *ImportError) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *ImportError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ImportError) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

// レコード作成
type CreateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ETCMeisaiRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_etc_meisai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRecordRequest) GetRecord() *ETCMeisaiRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type CreateRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ETCMeisaiRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordResponse) Reset() {
	*x = CreateRecordResponse{}
	mi := &file_etc_meisai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordResponse) ProtoMessage() {}

func (x *CreateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateRecordResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRecordResponse) GetRecord() *ETCMeisaiRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

// レコード取得
type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_etc_meisai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ETCMeisaiRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	mi := &file_etc_meisai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResponse.ProtoReflect.Descriptor instead.
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{7}
}

func (x *GetRecordResponse) GetRecord() *ETCMeisaiRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

// レコード一覧取得
type ListRecordsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Page      int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy    string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder SortOrder              `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=etc_meisai.v1.SortOrder" json:"sort_order,omitempty"`
	// フィルタ条件
	DateFrom      *string `protobuf:"bytes,5,opt,name=date_from,json=dateFrom,proto3,oneof" json:"date_from,omitempty"` // YYYY-MM-DD
	DateTo        *string `protobuf:"bytes,6,opt,name=date_to,json=dateTo,proto3,oneof" json:"date_to,omitempty"`       // YYYY-MM-DD
	CarNumber     *string `protobuf:"bytes,7,opt,name=car_number,json=carNumber,proto3,oneof" json:"car_number,omitempty"`
	EtcCardNumber *string `protobuf:"bytes,8,opt,name=etc_card_number,json=etcCardNumber,proto3,oneof" json:"etc_card_number,omitempty"`
	EntranceIc    *string `protobuf:"bytes,9,opt,name=entrance_ic,json=entranceIc,proto3,oneof" json:"entrance_ic,omitempty"`
	ExitIc        *string `protobuf:"bytes,10,opt,name=exit_ic,json=exitIc,proto3,oneof" json:"exit_ic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_etc_meisai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{8}
}

func (x *ListRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRecordsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListRecordsRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

func (x *ListRecordsRequest) GetDateFrom() string {
	if x != nil && x.DateFrom != nil {
		return *x.DateFrom
	}
	return ""
}

func (x *ListRecordsRequest) GetDateTo() string {
	if x != nil && x.DateTo != nil {
		return *x.DateTo
	}
	return ""
}

func (x *ListRecordsRequest) GetCarNumber() string {
	if x != nil && x.CarNumber != nil {
		return *x.CarNumber
	}
	return ""
}

func (x *ListRecordsRequest) GetEtcCardNumber() string {
	if x != nil && x.EtcCardNumber != nil {
		return *x.EtcCardNumber
	}
	return ""
}

func (x *ListRecordsRequest) GetEntranceIc() string {
	if x != nil && x.EntranceIc != nil {
		return *x.EntranceIc
	}
	return ""
}

func (x *ListRecordsRequest) GetExitIc() string {
	if x != nil && x.ExitIc != nil {
		return *x.ExitIc
	}
	return ""
}

type ListRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ETCMeisaiRecord     `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_etc_meisai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{9}
}

func (x *ListRecordsResponse) GetRecords() []*ETCMeisaiRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListRecordsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListRecordsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRecordsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// レコード更新
type UpdateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Record        *ETCMeisaiRecord       `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_etc_meisai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRecordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRecordRequest) GetRecord() *ETCMeisaiRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpdateRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ETCMeisaiRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordResponse) Reset() {
	*x = UpdateRecordResponse{}
	mi := &file_etc_meisai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordResponse) ProtoMessage() {}

func (x *UpdateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecordResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRecordResponse) GetRecord() *ETCMeisaiRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

// レコード削除
type DeleteRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_etc_meisai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRecordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// CSVインポート（ストリーミング）
type ImportCSVChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	ChunkNumber   int32                  `protobuf:"varint,4,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportCSVChunk) Reset() {
	*x = ImportCSVChunk{}
	mi := &file_etc_meisai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportCSVChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCSVChunk) ProtoMessage() {}

func (x *ImportCSVChunk) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCSVChunk.ProtoReflect.Descriptor instead.
func (*ImportCSVChunk) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{13}
}

func (x *ImportCSVChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ImportCSVChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImportCSVChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *ImportCSVChunk) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

type ImportProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProcessedRows      int32                  `protobuf:"varint,2,opt,name=processed_rows,json=processedRows,proto3" json:"processed_rows,omitempty"`
	SuccessRows        int32                  `protobuf:"varint,3,opt,name=success_rows,json=successRows,proto3" json:"success_rows,omitempty"`
	ErrorRows          int32                  `protobuf:"varint,4,opt,name=error_rows,json=errorRows,proto3" json:"error_rows,omitempty"`
	DuplicateRows      int32                  `protobuf:"varint,5,opt,name=duplicate_rows,json=duplicateRows,proto3" json:"duplicate_rows,omitempty"`
	ProgressPercentage float32                `protobuf:"fixed32,6,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	ErrorMessage       *string                `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	Status             ImportStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=etc_meisai.v1.ImportStatus" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ImportProgress) Reset() {
	*x = ImportProgress{}
	mi := &file_etc_meisai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProgress) ProtoMessage() {}

func (x *ImportProgress) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProgress.ProtoReflect.Descriptor instead.
func (*ImportProgress) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{14}
}

func (x *ImportProgress) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ImportProgress) GetProcessedRows() int32 {
	if x != nil {
		return x.ProcessedRows
	}
	return 0
}

func (x *ImportProgress) GetSuccessRows() int32 {
	if x != nil {
		return x.SuccessRows
	}
	return 0
}

func (x *ImportProgress) GetErrorRows() int32 {
	if x != nil {
		return x.ErrorRows
	}
	return 0
}

func (x *ImportProgress) GetDuplicateRows() int32 {
	if x != nil {
		return x.DuplicateRows
	}
	return 0
}

func (x *ImportProgress) GetProgressPercentage() float32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *ImportProgress) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *ImportProgress) GetStatus() ImportStatus {
	if x != nil {
		return x.Status
	}
	return ImportStatus_IMPORT_STATUS_UNSPECIFIED
}

// CSVインポート（単一リクエスト）
type ImportCSVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountType   string                 `protobuf:"bytes,1,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,4,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportCSVRequest) Reset() {
	*x = ImportCSVRequest{}
	mi := &file_etc_meisai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportCSVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCSVRequest) ProtoMessage() {}

func (x *ImportCSVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCSVRequest.ProtoReflect.Descriptor instead.
func (*ImportCSVRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{15}
}

func (x *ImportCSVRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *ImportCSVRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ImportCSVRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ImportCSVRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type ImportCSVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *ImportSession         `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportCSVResponse) Reset() {
	*x = ImportCSVResponse{}
	mi := &file_etc_meisai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportCSVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCSVResponse) ProtoMessage() {}

func (x *ImportCSVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCSVResponse.ProtoReflect.Descriptor instead.
func (*ImportCSVResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{16}
}

func (x *ImportCSVResponse) GetSession() *ImportSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// インポートセッション取得
type GetImportSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImportSessionRequest) Reset() {
	*x = GetImportSessionRequest{}
	mi := &file_etc_meisai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImportSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImportSessionRequest) ProtoMessage() {}

func (x *GetImportSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImportSessionRequest.ProtoReflect.Descriptor instead.
func (*GetImportSessionRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{17}
}

func (x *GetImportSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetImportSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *ImportSession         `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImportSessionResponse) Reset() {
	*x = GetImportSessionResponse{}
	mi := &file_etc_meisai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImportSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImportSessionResponse) ProtoMessage() {}

func (x *GetImportSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImportSessionResponse.ProtoReflect.Descriptor instead.
func (*GetImportSessionResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{18}
}

func (x *GetImportSessionResponse) GetSession() *ImportSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// インポートセッション一覧取得
type ListImportSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	AccountType   *string                `protobuf:"bytes,3,opt,name=account_type,json=accountType,proto3,oneof" json:"account_type,omitempty"`
	AccountId     *string                `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3,oneof" json:"account_id,omitempty"`
	Status        *ImportStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=etc_meisai.v1.ImportStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImportSessionsRequest) Reset() {
	*x = ListImportSessionsRequest{}
	mi := &file_etc_meisai_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImportSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportSessionsRequest) ProtoMessage() {}

func (x *ListImportSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListImportSessionsRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{19}
}

func (x *ListImportSessionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListImportSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListImportSessionsRequest) GetAccountType() string {
	if x != nil && x.AccountType != nil {
		return *x.AccountType
	}
	return ""
}

func (x *ListImportSessionsRequest) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *ListImportSessionsRequest) GetStatus() ImportStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ImportStatus_IMPORT_STATUS_UNSPECIFIED
}

type ListImportSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ImportSession       `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImportSessionsResponse) Reset() {
	*x = ListImportSessionsResponse{}
	mi := &file_etc_meisai_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImportSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportSessionsResponse) ProtoMessage() {}

func (x *ListImportSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListImportSessionsResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{20}
}

func (x *ListImportSessionsResponse) GetSessions() []*ImportSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListImportSessionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListImportSessionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListImportSessionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// マッピング作成
type CreateMappingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mapping       *ETCMapping            `protobuf:"bytes,1,opt,name=mapping,proto3" json:"mapping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMappingRequest) Reset() {
	*x = CreateMappingRequest{}
	mi := &file_etc_meisai_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMappingRequest) ProtoMessage() {}

func (x *CreateMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMappingRequest.ProtoReflect.Descriptor instead.
func (*CreateMappingRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{21}
}

func (x *CreateMappingRequest) GetMapping() *ETCMapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

type CreateMappingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mapping       *ETCMapping            `protobuf:"bytes,1,opt,name=mapping,proto3" json:"mapping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMappingResponse) Reset() {
	*x = CreateMappingResponse{}
	mi := &file_etc_meisai_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMappingResponse) ProtoMessage() {}

func (x *CreateMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMappingResponse.ProtoReflect.Descriptor instead.
func (*CreateMappingResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{22}
}

func (x *CreateMappingResponse) GetMapping() *ETCMapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

// マッピング取得
type GetMappingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMappingRequest) Reset() {
	*x = GetMappingRequest{}
	mi := &file_etc_meisai_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMappingRequest) ProtoMessage() {}

func (x *GetMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMappingRequest.ProtoReflect.Descriptor instead.
func (*GetMappingRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{23}
}

func (x *GetMappingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMappingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mapping       *ETCMapping            `protobuf:"bytes,1,opt,name=mapping,proto3" json:"mapping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMappingResponse) Reset() {
	*x = GetMappingResponse{}
	mi := &file_etc_meisai_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMappingResponse) ProtoMessage() {}

func (x *GetMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMappingResponse.ProtoReflect.Descriptor instead.
func (*GetMappingResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{24}
}

func (x *GetMappingResponse) GetMapping() *ETCMapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

// マッピング一覧取得
type ListMappingsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Page             int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	EtcRecordId      *int64                 `protobuf:"varint,3,opt,name=etc_record_id,json=etcRecordId,proto3,oneof" json:"etc_record_id,omitempty"`
	MappingType      *string                `protobuf:"bytes,4,opt,name=mapping_type,json=mappingType,proto3,oneof" json:"mapping_type,omitempty"`
	MappedEntityType *string                `protobuf:"bytes,5,opt,name=mapped_entity_type,json=mappedEntityType,proto3,oneof" json:"mapped_entity_type,omitempty"`
	MappedEntityId   *int64                 `protobuf:"varint,6,opt,name=mapped_entity_id,json=mappedEntityId,proto3,oneof" json:"mapped_entity_id,omitempty"`
	Status           *MappingStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=etc_meisai.v1.MappingStatus,oneof" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListMappingsRequest) Reset() {
	*x = ListMappingsRequest{}
	mi := &file_etc_meisai_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMappingsRequest) ProtoMessage() {}

func (x *ListMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMappingsRequest.ProtoReflect.Descriptor instead.
func (*ListMappingsRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{25}
}

func (x *ListMappingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMappingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMappingsRequest) GetEtcRecordId() int64 {
	if x != nil && x.EtcRecordId != nil {
		return *x.EtcRecordId
	}
	return 0
}

func (x *ListMappingsRequest) GetMappingType() string {
	if x != nil && x.MappingType != nil {
		return *x.MappingType
	}
	return ""
}

func (x *ListMappingsRequest) GetMappedEntityType() string {
	if x != nil && x.MappedEntityType != nil {
		return *x.MappedEntityType
	}
	return ""
}

func (x *ListMappingsRequest) GetMappedEntityId() int64 {
	if x != nil && x.MappedEntityId != nil {
		return *x.MappedEntityId
	}
	return 0
}

func (x *ListMappingsRequest) GetStatus() MappingStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return MappingStatus_MAPPING_STATUS_UNSPECIFIED
}

type ListMappingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mappings      []*ETCMapping          `protobuf:"bytes,1,rep,name=mappings,proto3" json:"mappings,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMappingsResponse) Reset() {
	*x = ListMappingsResponse{}
	mi := &file_etc_meisai_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMappingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMappingsResponse) ProtoMessage() {}

func (x *ListMappingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMappingsResponse.ProtoReflect.Descriptor instead.
func (*ListMappingsResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{26}
}

func (x *ListMappingsResponse) GetMappings() []*ETCMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

func (x *ListMappingsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMappingsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMappingsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// マッピング更新
type UpdateMappingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mapping       *ETCMapping            `protobuf:"bytes,2,opt,name=mapping,proto3" json:"mapping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMappingRequest) Reset() {
	*x = UpdateMappingRequest{}
	mi := &file_etc_meisai_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMappingRequest) ProtoMessage() {}

func (x *UpdateMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMappingRequest.ProtoReflect.Descriptor instead.
func (*UpdateMappingRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateMappingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMappingRequest) GetMapping() *ETCMapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

type UpdateMappingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mapping       *ETCMapping            `protobuf:"bytes,1,opt,name=mapping,proto3" json:"mapping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMappingResponse) Reset() {
	*x = UpdateMappingResponse{}
	mi := &file_etc_meisai_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMappingResponse) ProtoMessage() {}

func (x *UpdateMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMappingResponse.ProtoReflect.Descriptor instead.
func (*UpdateMappingResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateMappingResponse) GetMapping() *ETCMapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

// マッピング削除
type DeleteMappingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMappingRequest) Reset() {
	*x = DeleteMappingRequest{}
	mi := &file_etc_meisai_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMappingRequest) ProtoMessage() {}

func (x *DeleteMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMappingRequest.ProtoReflect.Descriptor instead.
func (*DeleteMappingRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteMappingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 統計情報取得
type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateFrom      *string                `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3,oneof" json:"date_from,omitempty"` // YYYY-MM-DD
	DateTo        *string                `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3,oneof" json:"date_to,omitempty"`       // YYYY-MM-DD
	CarNumber     *string                `protobuf:"bytes,3,opt,name=car_number,json=carNumber,proto3,oneof" json:"car_number,omitempty"`
	EtcCardNumber *string                `protobuf:"bytes,4,opt,name=etc_card_number,json=etcCardNumber,proto3,oneof" json:"etc_card_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_etc_meisai_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{30}
}

func (x *GetStatisticsRequest) GetDateFrom() string {
	if x != nil && x.DateFrom != nil {
		return *x.DateFrom
	}
	return ""
}

func (x *GetStatisticsRequest) GetDateTo() string {
	if x != nil && x.DateTo != nil {
		return *x.DateTo
	}
	return ""
}

func (x *GetStatisticsRequest) GetCarNumber() string {
	if x != nil && x.CarNumber != nil {
		return *x.CarNumber
	}
	return ""
}

func (x *GetStatisticsRequest) GetEtcCardNumber() string {
	if x != nil && x.EtcCardNumber != nil {
		return *x.EtcCardNumber
	}
	return ""
}

type GetStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRecords  int64                  `protobuf:"varint,1,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	UniqueCars    int32                  `protobuf:"varint,3,opt,name=unique_cars,json=uniqueCars,proto3" json:"unique_cars,omitempty"`
	UniqueCards   int32                  `protobuf:"varint,4,opt,name=unique_cards,json=uniqueCards,proto3" json:"unique_cards,omitempty"`
	DailyStats    []*DailyStatistics     `protobuf:"bytes,5,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	IcStats       []*ICStatistics        `protobuf:"bytes,6,rep,name=ic_stats,json=icStats,proto3" json:"ic_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	mi := &file_etc_meisai_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{31}
}

func (x *GetStatisticsResponse) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *GetStatisticsResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetStatisticsResponse) GetUniqueCars() int32 {
	if x != nil {
		return x.UniqueCars
	}
	return 0
}

func (x *GetStatisticsResponse) GetUniqueCards() int32 {
	if x != nil {
		return x.UniqueCards
	}
	return 0
}

func (x *GetStatisticsResponse) GetDailyStats() []*DailyStatistics {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

func (x *GetStatisticsResponse) GetIcStats() []*ICStatistics {
	if x != nil {
		return x.IcStats
	}
	return nil
}

type DailyStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	RecordCount   int32                  `protobuf:"varint,2,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyStatistics) Reset() {
	*x = DailyStatistics{}
	mi := &file_etc_meisai_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStatistics) ProtoMessage() {}

func (x *DailyStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStatistics.ProtoReflect.Descriptor instead.
func (*DailyStatistics) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{32}
}

func (x *DailyStatistics) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStatistics) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *DailyStatistics) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ICStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IcName        string                 `protobuf:"bytes,1,opt,name=ic_name,json=icName,proto3" json:"ic_name,omitempty"`
	UsageCount    int32                  `protobuf:"varint,2,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`
	IcType        string                 `protobuf:"bytes,3,opt,name=ic_type,json=icType,proto3" json:"ic_type,omitempty"` // entrance or exit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICStatistics) Reset() {
	*x = ICStatistics{}
	mi := &file_etc_meisai_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICStatistics) ProtoMessage() {}

func (x *ICStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_etc_meisai_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICStatistics.ProtoReflect.Descriptor instead.
func (*ICStatistics) Descriptor() ([]byte, []int) {
	return file_etc_meisai_proto_rawDescGZIP(), []int{33}
}

func (x *ICStatistics) GetIcName() string {
	if x != nil {
		return x.IcName
	}
	return ""
}

func (x *ICStatistics) GetUsageCount() int32 {
	if x != nil {
		return x.UsageCount
	}
	return 0
}

func (x *ICStatistics) GetIcType() string {
	if x != nil {
		return x.IcType
	}
	return ""
}

var File_etc_meisai_proto protoreflect.FileDescriptor

const file_etc_meisai_proto_rawDesc = "" +
	"\n" +
	"\x10etc_meisai.proto\x12\retc_meisai.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd7\x03\n" +
	"\x0fETCMeisaiRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\x12\x1f\n" +
	"\ventrance_ic\x18\x05 \x01(\tR\n" +
	"entranceIc\x12\x17\n" +
	"\aexit_ic\x18\x06 \x01(\tR\x06exitIc\x12\x1f\n" +
	"\vtoll_amount\x18\a \x01(\x05R\n" +
	"tollAmount\x12\x1d\n" +
	"\n" +
	"car_number\x18\b \x01(\tR\tcarNumber\x12&\n" +
	"\x0fetc_card_number\x18\t \x01(\tR\retcCardNumber\x12\x1c\n" +
	"\aetc_num\x18\n" +
	" \x01(\tH\x00R\x06etcNum\x88\x01\x01\x12%\n" +
	"\fdtako_row_id\x18\v \x01(\x03H\x01R\n" +
	"dtakoRowId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\n" +
	"\n" +
	"\b_etc_numB\x0f\n" +
	"\r_dtako_row_id\"\x9a\x04\n" +
	"\n" +
	"ETCMapping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\retc_record_id\x18\x02 \x01(\x03R\vetcRecordId\x12=\n" +
	"\n" +
	"etc_record\x18\x03 \x01(\v2\x1e.etc_meisai.v1.ETCMeisaiRecordR\tetcRecord\x12!\n" +
	"\fmapping_type\x18\x04 \x01(\tR\vmappingType\x12(\n" +
	"\x10mapped_entity_id\x18\x05 \x01(\x03R\x0emappedEntityId\x12,\n" +
	"\x12mapped_entity_type\x18\x06 \x01(\tR\x10mappedEntityType\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\x124\n" +
	"\x06status\x18\b \x01(\x0e2\x1c.etc_meisai.v1.MappingStatusR\x06status\x123\n" +
	"\bmetadata\x18\t \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_by\x18\n" +
	" \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa2\x05\n" +
	"\rImportSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\faccount_type\x18\x02 \x01(\tR\vaccountType\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.etc_meisai.v1.ImportStatusR\x06status\x12\x1d\n" +
	"\n" +
	"total_rows\x18\a \x01(\x05R\ttotalRows\x12%\n" +
	"\x0eprocessed_rows\x18\b \x01(\x05R\rprocessedRows\x12!\n" +
	"\fsuccess_rows\x18\t \x01(\x05R\vsuccessRows\x12\x1d\n" +
	"\n" +
	"error_rows\x18\n" +
	" \x01(\x05R\terrorRows\x12%\n" +
	"\x0eduplicate_rows\x18\v \x01(\x05R\rduplicateRows\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12B\n" +
	"\fcompleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vcompletedAt\x88\x01\x01\x127\n" +
	"\terror_log\x18\x0e \x03(\v2\x1a.etc_meisai.v1.ImportErrorR\berrorLog\x12\x1d\n" +
	"\n" +
	"created_by\x18\x0f \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0f\n" +
	"\r_completed_at\"\x8b\x01\n" +
	"\vImportError\x12\x1d\n" +
	"\n" +
	"row_number\x18\x01 \x01(\x05R\trowNumber\x12\x1d\n" +
	"\n" +
	"error_type\x18\x02 \x01(\tR\terrorType\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\braw_data\x18\x04 \x01(\tR\arawData\"M\n" +
	"\x13CreateRecordRequest\x126\n" +
	"\x06record\x18\x01 \x01(\v2\x1e.etc_meisai.v1.ETCMeisaiRecordR\x06record\"N\n" +
	"\x14CreateRecordResponse\x126\n" +
	"\x06record\x18\x01 \x01(\v2\x1e.etc_meisai.v1.ETCMeisaiRecordR\x06record\"\"\n" +
	"\x10GetRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x11GetRecordResponse\x126\n" +
	"\x06record\x18\x01 \x01(\v2\x1e.etc_meisai.v1.ETCMeisaiRecordR\x06record\"\xc5\x03\n" +
	"\x12ListRecordsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x127\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\x18.etc_meisai.v1.SortOrderR\tsortOrder\x12 \n" +
	"\tdate_from\x18\x05 \x01(\tH\x00R\bdateFrom\x88\x01\x01\x12\x1c\n" +
	"\adate_to\x18\x06 \x01(\tH\x01R\x06dateTo\x88\x01\x01\x12\"\n" +
	"\n" +
	"car_number\x18\a \x01(\tH\x02R\tcarNumber\x88\x01\x01\x12+\n" +
	"\x0fetc_card_number\x18\b \x01(\tH\x03R\retcCardNumber\x88\x01\x01\x12$\n" +
	"\ventrance_ic\x18\t \x01(\tH\x04R\n" +
	"entranceIc\x88\x01\x01\x12\x1c\n" +
	"\aexit_ic\x18\n" +
	" \x01(\tH\x05R\x06exitIc\x88\x01\x01B\f\n" +
	"\n" +
	"_date_fromB\n" +
	"\n" +
	"\b_date_toB\r\n" +
	"\v_car_numberB\x12\n" +
	"\x10_etc_card_numberB\x0e\n" +
	"\f_entrance_icB\n" +
	"\n" +
	"\b_exit_ic\"\xa1\x01\n" +
	"\x13ListRecordsResponse\x128\n" +
	"\arecords\x18\x01 \x03(\v2\x1e.etc_meisai.v1.ETCMeisaiRecordR\arecords\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"]\n" +
	"\x13UpdateRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x126\n" +
	"\x06record\x18\x02 \x01(\v2\x1e.etc_meisai.v1.ETCMeisaiRecordR\x06record\"N\n" +
	"\x14UpdateRecordResponse\x126\n" +
	"\x06record\x18\x01 \x01(\v2\x1e.etc_meisai.v1.ETCMeisaiRecordR\x06record\"%\n" +
	"\x13DeleteRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x7f\n" +
	"\x0eImportCSVChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\x12!\n" +
	"\fchunk_number\x18\x04 \x01(\x05R\vchunkNumber\"\xe1\x02\n" +
	"\x0eImportProgress\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0eprocessed_rows\x18\x02 \x01(\x05R\rprocessedRows\x12!\n" +
	"\fsuccess_rows\x18\x03 \x01(\x05R\vsuccessRows\x12\x1d\n" +
	"\n" +
	"error_rows\x18\x04 \x01(\x05R\terrorRows\x12%\n" +
	"\x0eduplicate_rows\x18\x05 \x01(\x05R\rduplicateRows\x12/\n" +
	"\x13progress_percentage\x18\x06 \x01(\x02R\x12progressPercentage\x12(\n" +
	"\rerror_message\x18\a \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x123\n" +
	"\x06status\x18\b \x01(\x0e2\x1b.etc_meisai.v1.ImportStatusR\x06statusB\x10\n" +
	"\x0e_error_message\"\x94\x01\n" +
	"\x10ImportCSVRequest\x12!\n" +
	"\faccount_type\x18\x01 \x01(\tR\vaccountType\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12!\n" +
	"\ffile_content\x18\x04 \x01(\fR\vfileContent\"K\n" +
	"\x11ImportCSVResponse\x126\n" +
	"\asession\x18\x01 \x01(\v2\x1c.etc_meisai.v1.ImportSessionR\asession\"8\n" +
	"\x17GetImportSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"R\n" +
	"\x18GetImportSessionResponse\x126\n" +
	"\asession\x18\x01 \x01(\v2\x1c.etc_meisai.v1.ImportSessionR\asession\"\xfd\x01\n" +
	"\x19ListImportSessionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12&\n" +
	"\faccount_type\x18\x03 \x01(\tH\x00R\vaccountType\x88\x01\x01\x12\"\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tH\x01R\taccountId\x88\x01\x01\x128\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.etc_meisai.v1.ImportStatusH\x02R\x06status\x88\x01\x01B\x0f\n" +
	"\r_account_typeB\r\n" +
	"\v_account_idB\t\n" +
	"\a_status\"\xa8\x01\n" +
	"\x1aListImportSessionsResponse\x128\n" +
	"\bsessions\x18\x01 \x03(\v2\x1c.etc_meisai.v1.ImportSessionR\bsessions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"K\n" +
	"\x14CreateMappingRequest\x123\n" +
	"\amapping\x18\x01 \x01(\v2\x19.etc_meisai.v1.ETCMappingR\amapping\"L\n" +
	"\x15CreateMappingResponse\x123\n" +
	"\amapping\x18\x01 \x01(\v2\x19.etc_meisai.v1.ETCMappingR\amapping\"#\n" +
	"\x11GetMappingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\x12GetMappingResponse\x123\n" +
	"\amapping\x18\x01 \x01(\v2\x19.etc_meisai.v1.ETCMappingR\amapping\"\x8e\x03\n" +
	"\x13ListMappingsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12'\n" +
	"\retc_record_id\x18\x03 \x01(\x03H\x00R\vetcRecordId\x88\x01\x01\x12&\n" +
	"\fmapping_type\x18\x04 \x01(\tH\x01R\vmappingType\x88\x01\x01\x121\n" +
	"\x12mapped_entity_type\x18\x05 \x01(\tH\x02R\x10mappedEntityType\x88\x01\x01\x12-\n" +
	"\x10mapped_entity_id\x18\x06 \x01(\x03H\x03R\x0emappedEntityId\x88\x01\x01\x129\n" +
	"\x06status\x18\a \x01(\x0e2\x1c.etc_meisai.v1.MappingStatusH\x04R\x06status\x88\x01\x01B\x10\n" +
	"\x0e_etc_record_idB\x0f\n" +
	"\r_mapping_typeB\x15\n" +
	"\x13_mapped_entity_typeB\x13\n" +
	"\x11_mapped_entity_idB\t\n" +
	"\a_status\"\x9f\x01\n" +
	"\x14ListMappingsResponse\x125\n" +
	"\bmappings\x18\x01 \x03(\v2\x19.etc_meisai.v1.ETCMappingR\bmappings\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"[\n" +
	"\x14UpdateMappingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x123\n" +
	"\amapping\x18\x02 \x01(\v2\x19.etc_meisai.v1.ETCMappingR\amapping\"L\n" +
	"\x15UpdateMappingResponse\x123\n" +
	"\amapping\x18\x01 \x01(\v2\x19.etc_meisai.v1.ETCMappingR\amapping\"&\n" +
	"\x14DeleteMappingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe4\x01\n" +
	"\x14GetStatisticsRequest\x12 \n" +
	"\tdate_from\x18\x01 \x01(\tH\x00R\bdateFrom\x88\x01\x01\x12\x1c\n" +
	"\adate_to\x18\x02 \x01(\tH\x01R\x06dateTo\x88\x01\x01\x12\"\n" +
	"\n" +
	"car_number\x18\x03 \x01(\tH\x02R\tcarNumber\x88\x01\x01\x12+\n" +
	"\x0fetc_card_number\x18\x04 \x01(\tH\x03R\retcCardNumber\x88\x01\x01B\f\n" +
	"\n" +
	"_date_fromB\n" +
	"\n" +
	"\b_date_toB\r\n" +
	"\v_car_numberB\x12\n" +
	"\x10_etc_card_number\"\x9c\x02\n" +
	"\x15GetStatisticsResponse\x12#\n" +
	"\rtotal_records\x18\x01 \x01(\x03R\ftotalRecords\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x03R\vtotalAmount\x12\x1f\n" +
	"\vunique_cars\x18\x03 \x01(\x05R\n" +
	"uniqueCars\x12!\n" +
	"\funique_cards\x18\x04 \x01(\x05R\vuniqueCards\x12?\n" +
	"\vdaily_stats\x18\x05 \x03(\v2\x1e.etc_meisai.v1.DailyStatisticsR\n" +
	"dailyStats\x126\n" +
	"\bic_stats\x18\x06 \x03(\v2\x1b.etc_meisai.v1.ICStatisticsR\aicStats\"k\n" +
	"\x0fDailyStatistics\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12!\n" +
	"\frecord_count\x18\x02 \x01(\x05R\vrecordCount\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\"a\n" +
	"\fICStatistics\x12\x17\n" +
	"\aic_name\x18\x01 \x01(\tR\x06icName\x12\x1f\n" +
	"\vusage_count\x18\x02 \x01(\x05R\n" +
	"usageCount\x12\x17\n" +
	"\aic_type\x18\x03 \x01(\tR\x06icType*\xa0\x01\n" +
	"\rMappingStatus\x12\x1e\n" +
	"\x1aMAPPING_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MAPPING_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17MAPPING_STATUS_INACTIVE\x10\x02\x12\x1a\n" +
	"\x16MAPPING_STATUS_PENDING\x10\x03\x12\x1b\n" +
	"\x17MAPPING_STATUS_REJECTED\x10\x04*\xba\x01\n" +
	"\fImportStatus\x12\x1d\n" +
	"\x19IMPORT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15IMPORT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18IMPORT_STATUS_PROCESSING\x10\x02\x12\x1b\n" +
	"\x17IMPORT_STATUS_COMPLETED\x10\x03\x12\x18\n" +
	"\x14IMPORT_STATUS_FAILED\x10\x04\x12\x1b\n" +
	"\x17IMPORT_STATUS_CANCELLED\x10\x05*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x022\xa1\x0f\n" +
	"\x10ETCMeisaiService\x12\x83\x01\n" +
	"\fCreateRecord\x12\".etc_meisai.v1.CreateRecordRequest\x1a#.etc_meisai.v1.CreateRecordResponse\"*\x82\xd3\xe4\x93\x02$:\x06record\"\x1a/api/v1/etc-meisai/records\x12w\n" +
	"\tGetRecord\x12\x1f.etc_meisai.v1.GetRecordRequest\x1a .etc_meisai.v1.GetRecordResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/etc-meisai/records/{id}\x12x\n" +
	"\vListRecords\x12!.etc_meisai.v1.ListRecordsRequest\x1a\".etc_meisai.v1.ListRecordsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/etc-meisai/records\x12\x88\x01\n" +
	"\fUpdateRecord\x12\".etc_meisai.v1.UpdateRecordRequest\x1a#.etc_meisai.v1.UpdateRecordResponse\"/\x82\xd3\xe4\x93\x02):\x06record\x1a\x1f/api/v1/etc-meisai/records/{id}\x12s\n" +
	"\fDeleteRecord\x12\".etc_meisai.v1.DeleteRecordRequest\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!*\x1f/api/v1/etc-meisai/records/{id}\x12U\n" +
	"\x0fImportCSVStream\x12\x1d.etc_meisai.v1.ImportCSVChunk\x1a\x1d.etc_meisai.v1.ImportProgress\"\x00(\x010\x01\x12t\n" +
	"\tImportCSV\x12\x1f.etc_meisai.v1.ImportCSVRequest\x1a .etc_meisai.v1.ImportCSVResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/etc-meisai/import\x12\x9c\x01\n" +
	"\x10GetImportSession\x12&.etc_meisai.v1.GetImportSessionRequest\x1a'.etc_meisai.v1.GetImportSessionResponse\"7\x82\xd3\xe4\x93\x021\x12//api/v1/etc-meisai/import-sessions/{session_id}\x12\x95\x01\n" +
	"\x12ListImportSessions\x12(.etc_meisai.v1.ListImportSessionsRequest\x1a).etc_meisai.v1.ListImportSessionsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/etc-meisai/import-sessions\x12\x88\x01\n" +
	"\rCreateMapping\x12#.etc_meisai.v1.CreateMappingRequest\x1a$.etc_meisai.v1.CreateMappingResponse\",\x82\xd3\xe4\x93\x02&:\amapping\"\x1b/api/v1/etc-meisai/mappings\x12{\n" +
	"\n" +
	"GetMapping\x12 .etc_meisai.v1.GetMappingRequest\x1a!.etc_meisai.v1.GetMappingResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/etc-meisai/mappings/{id}\x12|\n" +
	"\fListMappings\x12\".etc_meisai.v1.ListMappingsRequest\x1a#.etc_meisai.v1.ListMappingsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/etc-meisai/mappings\x12\x8d\x01\n" +
	"\rUpdateMapping\x12#.etc_meisai.v1.UpdateMappingRequest\x1a$.etc_meisai.v1.UpdateMappingResponse\"1\x82\xd3\xe4\x93\x02+:\amapping\x1a /api/v1/etc-meisai/mappings/{id}\x12v\n" +
	"\rDeleteMapping\x12#.etc_meisai.v1.DeleteMappingRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\"* /api/v1/etc-meisai/mappings/{id}\x12\x81\x01\n" +
	"\rGetStatistics\x12#.etc_meisai.v1.GetStatisticsRequest\x1a$.etc_meisai.v1.GetStatisticsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/etc-meisai/statisticsB/Z-github.com/yhonda-ohishi/etc_meisai/src/pb;pbb\x06proto3"

var (
	file_etc_meisai_proto_rawDescOnce sync.Once
	file_etc_meisai_proto_rawDescData []byte
)

func file_etc_meisai_proto_rawDescGZIP() []byte {
	file_etc_meisai_proto_rawDescOnce.Do(func() {
		file_etc_meisai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_etc_meisai_proto_rawDesc), len(file_etc_meisai_proto_rawDesc)))
	})
	return file_etc_meisai_proto_rawDescData
}

var file_etc_meisai_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_etc_meisai_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_etc_meisai_proto_goTypes = []any{
	(MappingStatus)(0),                 // 0: etc_meisai.v1.MappingStatus
	(ImportStatus)(0),                  // 1: etc_meisai.v1.ImportStatus
	(SortOrder)(0),                     // 2: etc_meisai.v1.SortOrder
	(*ETCMeisaiRecord)(nil),            // 3: etc_meisai.v1.ETCMeisaiRecord
	(*ETCMapping)(nil),                 // 4: etc_meisai.v1.ETCMapping
	(*ImportSession)(nil),              // 5: etc_meisai.v1.ImportSession
	(*ImportError)(nil),                // 6: etc_meisai.v1.ImportError
	(*CreateRecordRequest)(nil),        // 7: etc_meisai.v1.CreateRecordRequest
	(*CreateRecordResponse)(nil),       // 8: etc_meisai.v1.CreateRecordResponse
	(*GetRecordRequest)(nil),           // 9: etc_meisai.v1.GetRecordRequest
	(*GetRecordResponse)(nil),          // 10: etc_meisai.v1.GetRecordResponse
	(*ListRecordsRequest)(nil),         // 11: etc_meisai.v1.ListRecordsRequest
	(*ListRecordsResponse)(nil),        // 12: etc_meisai.v1.ListRecordsResponse
	(*UpdateRecordRequest)(nil),        // 13: etc_meisai.v1.UpdateRecordRequest
	(*UpdateRecordResponse)(nil),       // 14: etc_meisai.v1.UpdateRecordResponse
	(*DeleteRecordRequest)(nil),        // 15: etc_meisai.v1.DeleteRecordRequest
	(*ImportCSVChunk)(nil),             // 16: etc_meisai.v1.ImportCSVChunk
	(*ImportProgress)(nil),             // 17: etc_meisai.v1.ImportProgress
	(*ImportCSVRequest)(nil),           // 18: etc_meisai.v1.ImportCSVRequest
	(*ImportCSVResponse)(nil),          // 19: etc_meisai.v1.ImportCSVResponse
	(*GetImportSessionRequest)(nil),    // 20: etc_meisai.v1.GetImportSessionRequest
	(*GetImportSessionResponse)(nil),   // 21: etc_meisai.v1.GetImportSessionResponse
	(*ListImportSessionsRequest)(nil),  // 22: etc_meisai.v1.ListImportSessionsRequest
	(*ListImportSessionsResponse)(nil), // 23: etc_meisai.v1.ListImportSessionsResponse
	(*CreateMappingRequest)(nil),       // 24: etc_meisai.v1.CreateMappingRequest
	(*CreateMappingResponse)(nil),      // 25: etc_meisai.v1.CreateMappingResponse
	(*GetMappingRequest)(nil),          // 26: etc_meisai.v1.GetMappingRequest
	(*GetMappingResponse)(nil),         // 27: etc_meisai.v1.GetMappingResponse
	(*ListMappingsRequest)(nil),        // 28: etc_meisai.v1.ListMappingsRequest
	(*ListMappingsResponse)(nil),       // 29: etc_meisai.v1.ListMappingsResponse
	(*UpdateMappingRequest)(nil),       // 30: etc_meisai.v1.UpdateMappingRequest
	(*UpdateMappingResponse)(nil),      // 31: etc_meisai.v1.UpdateMappingResponse
	(*DeleteMappingRequest)(nil),       // 32: etc_meisai.v1.DeleteMappingRequest
	(*GetStatisticsRequest)(nil),       // 33: etc_meisai.v1.GetStatisticsRequest
	(*GetStatisticsResponse)(nil),      // 34: etc_meisai.v1.GetStatisticsResponse
	(*DailyStatistics)(nil),            // 35: etc_meisai.v1.DailyStatistics
	(*ICStatistics)(nil),               // 36: etc_meisai.v1.ICStatistics
	(*timestamppb.Timestamp)(nil),      // 37: google.protobuf.Timestamp
	(*structpb.Struct)(nil),            // 38: google.protobuf.Struct
	(*emptypb.Empty)(nil),              // 39: google.protobuf.Empty
}
var file_etc_meisai_proto_depIdxs = []int32{
	37, // 0: etc_meisai.v1.ETCMeisaiRecord.created_at:type_name -> google.protobuf.Timestamp
	37, // 1: etc_meisai.v1.ETCMeisaiRecord.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 2: etc_meisai.v1.ETCMapping.etc_record:type_name -> etc_meisai.v1.ETCMeisaiRecord
	0,  // 3: etc_meisai.v1.ETCMapping.status:type_name -> etc_meisai.v1.MappingStatus
	38, // 4: etc_meisai.v1.ETCMapping.metadata:type_name -> google.protobuf.Struct
	37, // 5: etc_meisai.v1.ETCMapping.created_at:type_name -> google.protobuf.Timestamp
	37, // 6: etc_meisai.v1.ETCMapping.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 7: etc_meisai.v1.ImportSession.status:type_name -> etc_meisai.v1.ImportStatus
	37, // 8: etc_meisai.v1.ImportSession.started_at:type_name -> google.protobuf.Timestamp
	37, // 9: etc_meisai.v1.ImportSession.completed_at:type_name -> google.protobuf.Timestamp
	6,  // 10: etc_meisai.v1.ImportSession.error_log:type_name -> etc_meisai.v1.ImportError
	37, // 11: etc_meisai.v1.ImportSession.created_at:type_name -> google.protobuf.Timestamp
	3,  // 12: etc_meisai.v1.CreateRecordRequest.record:type_name -> etc_meisai.v1.ETCMeisaiRecord
	3,  // 13: etc_meisai.v1.CreateRecordResponse.record:type_name -> etc_meisai.v1.ETCMeisaiRecord
	3,  // 14: etc_meisai.v1.GetRecordResponse.record:type_name -> etc_meisai.v1.ETCMeisaiRecord
	2,  // 15: etc_meisai.v1.ListRecordsRequest.sort_order:type_name -> etc_meisai.v1.SortOrder
	3,  // 16: etc_meisai.v1.ListRecordsResponse.records:type_name -> etc_meisai.v1.ETCMeisaiRecord
	3,  // 17: etc_meisai.v1.UpdateRecordRequest.record:type_name -> etc_meisai.v1.ETCMeisaiRecord
	3,  // 18: etc_meisai.v1.UpdateRecordResponse.record:type_name -> etc_meisai.v1.ETCMeisaiRecord
	1,  // 19: etc_meisai.v1.ImportProgress.status:type_name -> etc_meisai.v1.ImportStatus
	5,  // 20: etc_meisai.v1.ImportCSVResponse.session:type_name -> etc_meisai.v1.ImportSession
	5,  // 21: etc_meisai.v1.GetImportSessionResponse.session:type_name -> etc_meisai.v1.ImportSession
	1,  // 22: etc_meisai.v1.ListImportSessionsRequest.status:type_name -> etc_meisai.v1.ImportStatus
	5,  // 23: etc_meisai.v1.ListImportSessionsResponse.sessions:type_name -> etc_meisai.v1.ImportSession
	4,  // 24: etc_meisai.v1.CreateMappingRequest.mapping:type_name -> etc_meisai.v1.ETCMapping
	4,  // 25: etc_meisai.v1.CreateMappingResponse.mapping:type_name -> etc_meisai.v1.ETCMapping
	4,  // 26: etc_meisai.v1.GetMappingResponse.mapping:type_name -> etc_meisai.v1.ETCMapping
	0,  // 27: etc_meisai.v1.ListMappingsRequest.status:type_name -> etc_meisai.v1.MappingStatus
	4,  // 28: etc_meisai.v1.ListMappingsResponse.mappings:type_name -> etc_meisai.v1.ETCMapping
	4,  // 29: etc_meisai.v1.UpdateMappingRequest.mapping:type_name -> etc_meisai.v1.ETCMapping
	4,  // 30: etc_meisai.v1.UpdateMappingResponse.mapping:type_name -> etc_meisai.v1.ETCMapping
	35, // 31: etc_meisai.v1.GetStatisticsResponse.daily_stats:type_name -> etc_meisai.v1.DailyStatistics
	36, // 32: etc_meisai.v1.GetStatisticsResponse.ic_stats:type_name -> etc_meisai.v1.ICStatistics
	7,  // 33: etc_meisai.v1.ETCMeisaiService.CreateRecord:input_type -> etc_meisai.v1.CreateRecordRequest
	9,  // 34: etc_meisai.v1.ETCMeisaiService.GetRecord:input_type -> etc_meisai.v1.GetRecordRequest
	11, // 35: etc_meisai.v1.ETCMeisaiService.ListRecords:input_type -> etc_meisai.v1.ListRecordsRequest
	13, // 36: etc_meisai.v1.ETCMeisaiService.UpdateRecord:input_type -> etc_meisai.v1.UpdateRecordRequest
	15, // 37: etc_meisai.v1.ETCMeisaiService.DeleteRecord:input_type -> etc_meisai.v1.DeleteRecordRequest
	16, // 38: etc_meisai.v1.ETCMeisaiService.ImportCSVStream:input_type -> etc_meisai.v1.ImportCSVChunk
	18, // 39: etc_meisai.v1.ETCMeisaiService.ImportCSV:input_type -> etc_meisai.v1.ImportCSVRequest
	20, // 40: etc_meisai.v1.ETCMeisaiService.GetImportSession:input_type -> etc_meisai.v1.GetImportSessionRequest
	22, // 41: etc_meisai.v1.ETCMeisaiService.ListImportSessions:input_type -> etc_meisai.v1.ListImportSessionsRequest
	24, // 42: etc_meisai.v1.ETCMeisaiService.CreateMapping:input_type -> etc_meisai.v1.CreateMappingRequest
	26, // 43: etc_meisai.v1.ETCMeisaiService.GetMapping:input_type -> etc_meisai.v1.GetMappingRequest
	28, // 44: etc_meisai.v1.ETCMeisaiService.ListMappings:input_type -> etc_meisai.v1.ListMappingsRequest
	30, // 45: etc_meisai.v1.ETCMeisaiService.UpdateMapping:input_type -> etc_meisai.v1.UpdateMappingRequest
	32, // 46: etc_meisai.v1.ETCMeisaiService.DeleteMapping:input_type -> etc_meisai.v1.DeleteMappingRequest
	33, // 47: etc_meisai.v1.ETCMeisaiService.GetStatistics:input_type -> etc_meisai.v1.GetStatisticsRequest
	8,  // 48: etc_meisai.v1.ETCMeisaiService.CreateRecord:output_type -> etc_meisai.v1.CreateRecordResponse
	10, // 49: etc_meisai.v1.ETCMeisaiService.GetRecord:output_type -> etc_meisai.v1.GetRecordResponse
	12, // 50: etc_meisai.v1.ETCMeisaiService.ListRecords:output_type -> etc_meisai.v1.ListRecordsResponse
	14, // 51: etc_meisai.v1.ETCMeisaiService.UpdateRecord:output_type -> etc_meisai.v1.UpdateRecordResponse
	39, // 52: etc_meisai.v1.ETCMeisaiService.DeleteRecord:output_type -> google.protobuf.Empty
	17, // 53: etc_meisai.v1.ETCMeisaiService.ImportCSVStream:output_type -> etc_meisai.v1.ImportProgress
	19, // 54: etc_meisai.v1.ETCMeisaiService.ImportCSV:output_type -> etc_meisai.v1.ImportCSVResponse
	21, // 55: etc_meisai.v1.ETCMeisaiService.GetImportSession:output_type -> etc_meisai.v1.GetImportSessionResponse
	23, // 56: etc_meisai.v1.ETCMeisaiService.ListImportSessions:output_type -> etc_meisai.v1.ListImportSessionsResponse
	25, // 57: etc_meisai.v1.ETCMeisaiService.CreateMapping:output_type -> etc_meisai.v1.CreateMappingResponse
	27, // 58: etc_meisai.v1.ETCMeisaiService.GetMapping:output_type -> etc_meisai.v1.GetMappingResponse
	29, // 59: etc_meisai.v1.ETCMeisaiService.ListMappings:output_type -> etc_meisai.v1.ListMappingsResponse
	31, // 60: etc_meisai.v1.ETCMeisaiService.UpdateMapping:output_type -> etc_meisai.v1.UpdateMappingResponse
	39, // 61: etc_meisai.v1.ETCMeisaiService.DeleteMapping:output_type -> google.protobuf.Empty
	34, // 62: etc_meisai.v1.ETCMeisaiService.GetStatistics:output_type -> etc_meisai.v1.GetStatisticsResponse
	48, // [48:63] is the sub-list for method output_type
	33, // [33:48] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_etc_meisai_proto_init() }
func file_etc_meisai_proto_init() {
	if File_etc_meisai_proto != nil {
		return
	}
	file_etc_meisai_proto_msgTypes[0].OneofWrappers = []any{}
	file_etc_meisai_proto_msgTypes[2].OneofWrappers = []any{}
	file_etc_meisai_proto_msgTypes[8].OneofWrappers = []any{}
	file_etc_meisai_proto_msgTypes[14].OneofWrappers = []any{}
	file_etc_meisai_proto_msgTypes[19].OneofWrappers = []any{}
	file_etc_meisai_proto_msgTypes[25].OneofWrappers = []any{}
	file_etc_meisai_proto_msgTypes[30].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_etc_meisai_proto_rawDesc), len(file_etc_meisai_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_etc_meisai_proto_goTypes,
		DependencyIndexes: file_etc_meisai_proto_depIdxs,
		EnumInfos:         file_etc_meisai_proto_enumTypes,
		MessageInfos:      file_etc_meisai_proto_msgTypes,
	}.Build()
	File_etc_meisai_proto = out.File
	file_etc_meisai_proto_goTypes = nil
	file_etc_meisai_proto_depIdxs = nil
}
