#!/bin/bash
# T013-B: Optimized parallel test runner
# Generated by test-optimizer.go

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${YELLOW}Running optimized parallel tests...${NC}"

# Start timing
START_TIME=$(date +%s)

# Function to run tests for a package group
run_test_group() {
    local group=$1
    echo "Testing group: $group"
    go test -v -parallel 4 $group
}

# Export function for parallel execution
export -f run_test_group

# Group 1: Fast, parallelizable packages
FAST_PACKAGES=(
    github.com/yhonda-ohishi/etc_meisai/tests/integration
    github.com/yhonda-ohishi/etc_meisai/tests/performance
    github.com/yhonda-ohishi/etc_meisai/tests/unit/handlers
    github.com/yhonda-ohishi/etc_meisai/src/services
    github.com/yhonda-ohishi/etc_meisai/tests/contract
    github.com/yhonda-ohishi/etc_meisai/tests/security
    github.com/yhonda-ohishi/etc_meisai/tests/unit/grpc
    github.com/yhonda-ohishi/etc_meisai/tests/unit/middleware
    github.com/yhonda-ohishi/etc_meisai/src/repositories
    github.com/yhonda-ohishi/etc_meisai/tests/fixtures
)

# Group 2: Medium speed packages
MEDIUM_PACKAGES=(
)

# Group 3: Slow or sequential packages
SLOW_PACKAGES=(
)

# Run fast packages in parallel
echo -e "${GREEN}Running fast packages in parallel...${NC}"
printf "%s\n" "${FAST_PACKAGES[@]}" | xargs -P 4 -I {} bash -c 'run_test_group "$@"' _ {}

# Run medium packages with limited parallelism
echo -e "${GREEN}Running medium packages...${NC}"
printf "%s\n" "${MEDIUM_PACKAGES[@]}" | xargs -P 2 -I {} bash -c 'run_test_group "$@"' _ {}

# Run slow packages sequentially
echo -e "${GREEN}Running slow packages...${NC}"
for pkg in "${SLOW_PACKAGES[@]}"; do
    run_test_group "$pkg"
done

# Calculate duration
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

echo -e "${GREEN}All tests completed in ${DURATION} seconds${NC}"

# Check if we met the target
if [ $DURATION -gt 30 ]; then
    echo -e "${RED}⚠ Tests took longer than 30 seconds target${NC}"
    exit 1
else
    echo -e "${GREEN}✅ Tests completed within 30 seconds target${NC}"
fi
